-- ==============================================================================
-- Migration: Fix Supabase RLS and Enable Cross-Branch Attendance & Owner Access
-- Run this in your Supabase Dashboard -> SQL Editor
-- ==============================================================================

-- 1. Ensure Attendance table has punch in/out columns
ALTER TABLE public."Attendance"
    ADD COLUMN IF NOT EXISTS "punchIn" text,
    ADD COLUMN IF NOT EXISTS "punchOut" text,
    ADD COLUMN IF NOT EXISTS "notes" text,
    ADD COLUMN IF NOT EXISTS "updatedBy" text;

CREATE INDEX IF NOT EXISTS "attendance_staff_date_idx" 
    ON public."Attendance" ("staffId", date);

-- 2. Fix Row-Level Security on Attendance (Allows staff interchange across all branches)
ALTER TABLE public."Attendance" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "branch_insert" ON public."Attendance";
DROP POLICY IF EXISTS "branch_read" ON public."Attendance";
DROP POLICY IF EXISTS "branch_update" ON public."Attendance";
DROP POLICY IF EXISTS "allow_attendance_all" ON public."Attendance";
DROP POLICY IF EXISTS "allow_all_attendance" ON public."Attendance";

-- Grant full select/insert/update/delete on Attendance for both authenticated and anon
CREATE POLICY "allow_all_attendance"
    ON public."Attendance"
    FOR ALL
    TO public
    USING (true)
    WITH CHECK (true);

-- 3. Fix Row-Level Security on Staff (Allows viewing staff across branches for rotation)
ALTER TABLE public."Staff" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "staff_read_all" ON public."Staff";
DROP POLICY IF EXISTS "allow_all_staff" ON public."Staff";

CREATE POLICY "allow_all_staff"
    ON public."Staff"
    FOR ALL
    TO public
    USING (true)
    WITH CHECK (true);

-- 4. Fix Row-Level Security on Invoices, Clients, Appointments, and Expenses
ALTER TABLE public."Expense" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all_expense" ON public."Expense";
CREATE POLICY "allow_all_expense" ON public."Expense" FOR ALL TO public USING (true) WITH CHECK (true);

ALTER TABLE public."ManualDailySales" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all access to ManualDailySales" ON public."ManualDailySales";
CREATE POLICY "Allow all access to ManualDailySales" ON public."ManualDailySales" FOR ALL TO public USING (true) WITH CHECK (true);

-- 5. Confirm or create Owner account in Supabase Auth (auth.users)
-- Sets email_confirmed_at and assigns role 'owner' so owner@christalinmirrors.com can sign in directly
-- Note: 'confirmed_at' is automatically generated by Postgres from 'email_confirmed_at'
UPDATE auth.users
SET email_confirmed_at = COALESCE(email_confirmed_at, now()),
    raw_app_meta_data = jsonb_set(COALESCE(raw_app_meta_data, '{}'::jsonb), '{role}', '"owner"'),
    raw_user_meta_data = jsonb_set(COALESCE(raw_user_meta_data, '{}'::jsonb), '{role}', '"owner"')
WHERE email = 'owner@christalinmirrors.com';
