version: '3.8'

services:
  frontend:
    build: .
    container_name: sunpro_frontend
    ports:
      - "80:80"
    restart: always
    networks:
      - sunpro_network

networks:
  sunpro_network:
    driver: bridge
